Import([
	'env',
])

env=env.Clone(CPPPATH=[Dir('../common')])

masterLib=env.SharedLibrary(
	target='DictationBridgeMaster64' if env['TARGET_ARCH'] == 'x86_64' else 'DictationBridgeMaster32',
	source=[
		'main.cpp',
		'master.def',
	],
	LIBS=[
		'shell32',
		'user32',
	],
)

Return('masterLib')
